### ISSUE TITLE
Swipe to dismiss doesn't remove the card permanently

### ISSUE THREAD

**Issue by kiaanpillay** [nisrulz/recyclerviewhelper#3] opened 2016-07-08 00:57 UTC
I am using your swipe to dismiss feature and it removes the card and even deletes the object from the list but messes up with the animation.

If I delete the card there is just a big grey space where it was and if I scroll down and then back up again the old card is still there where the gray space was but it is deleted from the actual list.

searchList.remove(position);
notifyItemRemoved(position);

Thats my code on item dismiss

**Comment by nisrulz** [comment] 2016-07-08 08:53
Just verified and confirming the sample app works as intended and there is no such issue as you have mentioned in above. 

You need to either share your code or post more information for me to debug and suggest what you might be doing wrong.

**Comment by nisrulz** [comment] 2016-08-01 18:01
Closing as OP hasn't responded since 24 days and I have verified that this is not the issue in the code thats published.

**Closed by nisrulz** 2016-08-01 18:01 UTC
